# Custom Language File for Launcher Customizer

[ejs.app]
title = "Wynaria"

[ejs.landing]
mediaGitHubURL = "https://github.com/mc-wynaria/launcher"
mediaTwitterURL = "https://twitter.wynaria.fr/"
mediaInstagramURL = "https://instagram.wynaria.Fr/"
mediaYouTubeURL = "https://youtube.wynaria.fr/"
mediaDiscordURL = "https://discord.gg/wynaria"

[ejs.settings]
sourceGithubLink = "https://github.com/mc-wynaria/launcher"
supportLink = "https://support.wynaria.fr"

[ejs.welcome]
welcomeHeader = "Rejoignez Wynaria !"
welcomeDescription = "Wynaria est un serveur de type Survie Custom avec des dimensions custom et du rp comme du j'amais vue !"
welcomeDescCTA = "Lancez-vous dans l'aventure !"
